# Script to generate a classification chart of function type for SNP annotation
# @author cxiang

#parse the arguments
args = commandArgs(trailing = TRUE)
annofile = "WGC081212-DNW06_combined.hg19_multianno.csv"
outfigure = args[2]
con = read.csv(annofile)
data = data.frame(row.names = 1)
for (i in con[,9]){
    if (is.null(data[[i]])) {
      data[[i]] = 0
    }
    else{
      data[[i]] = data[[i]] + 1
    }
}
# write sorted list of function type generated by the ammounts
data = data[,-which(colnames(data) == ".")]
write.csv(
  sort(data, decreasing = T),
  file = paste(outfigure, ".csv", sep = ""),
  row.names = F
)
# plot the list of function type
pdf(paste(outfigure, ".pdf", sep = ""),paper = 'a4')
cols = rep("steelblue", length(data))
barplot(
  as.matrix(sort(data, decreasing = T), rownames.force = F),
  col = cols,
  width = 1,
  space = 1,
  #xlab = "Function Type",
  ylab = "SNP/INDEL Number",
  #las = 1,
  main = "Exonic Variant Type",
  axisnames = F
)
text(
  x = seq(1.5, 2 * length(data), by = 2),
  y = 0,
  srt = 45,
  adj = 1,
  labels = names(sort(data, decreasing = T)),
  xpd = TRUE
)
dev.off()
