# Script to generate a classification chart of function type for SNP annotation
# @author cxiang

#parse the arguments
args = commandArgs(trailing = TRUE)
annofile = args[1]
outfigure = args[2]
con = file(annofile, "r")
line = readLines(con, n = 1)
line = readLines(con, n = 1)
data = data.frame(row.names = 1)
while (length(line) > 0) {
  #print(line)
  spl = gsub('"', '', strsplit(line, ",")[[1]][6])
  sp = strsplit(spl, ";")[[1]]
  for (i in sp) {
    if (is.null(data[[i]])) {
      data[[i]] = 0
    }
    else{
      data[[i]] = data[[i]] + 1
    }
  }
  line = readLines(con, n = 1)
}
# write sorted list of function type generated by the ammounts
colnames(data)[which(colnames(data) == ".")] = "Other"
write.csv(
  sort(data, decreasing = T),
  file = paste(outfigure, ".csv", sep = ""),
  row.names = F
)
# plot the list of function type
pdf(paste(outfigure, ".pdf", sep = ""), paper = 'a4')
cols = rep("steelblue", length(data))
barplot(
  as.matrix(sort(data, decreasing = T), rownames.force = F),
  col = cols,
  width = 1,
  space = 1,
  #xlab = "Function Type",
  ylab = "SNP/INDEL Number",
  #las = 1,
  main = "Variant Function Type",
  axisnames = F
)
text(
  x = seq(1.5, 2 * length(data), by = 2),
  y = 0,
  srt = 45,
  adj = 1,
  labels = names(sort(data, decreasing = T)),
  xpd = TRUE
)
dev.off()
